---

- name: Install apt packages
  become: yes
  apt:
    pkg:
    - htop
    - tmux
    - bat
    - tree
    - zsh
    - vim
    - appmenu-gtk3-module
    - gnome-tweaks
    - tlp
    - poppler-utils
    - autojump
    - npm
    - language-pack-gnome-he
    - gir1.2-gmenu-3.0

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
