---

- name: Install apt packages
  become: yes
  apt:
    pkg:
    - htop
    - tmux
    - bat
    - tree
    - zsh
    - vim
    - appmenu-gtk3-module
    - gnome-tweaks
    - tlp
    - poppler-utils
    - autojump
    - npm

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes